# Generated by Django 3.0.8 on 2020-07-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsfile',
            name='date',
            field=models.DateTimeField(max_length=100),
        ),
    ]
