# Generated by Django 3.0.8 on 2020-07-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200721_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsfile',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
